const connection = require('../database/connection');

module.exports = {
    async index (request,response) {
        const [count] = await connection('rdcs_response').count();
        response.header('X-Total-Count', count['count(*)']);

        const rdcresponse = await connection('rdcs_response').select('*');
        return response.json(rdcresponse);
      },

    async create (request, response){        
        const { 
            area,
            cod,
            obra,
            rain,
            redalert,           
            area_activity1,           
            cod_activity1,
            description_activity1,
            report1,
            area_activity2,           
            cod_activity2,
            description_activity2,
            report2,
            area_activity3,           
            cod_activity3,
            description_activity3,
            report3,
            area_activity4,           
            cod_activity4,
            description_activity4,
            report4,
            area_activity5,           
            cod_activity5,
            description_activity5,
            report5,
            area_activity6,           
            cod_activity6,
            description_activity6,
            report6,
            name_employee1,
            cod_employee1,
            occupation_employee1,
            hr_1_ativ,
            name_employee2,
            cod_employee2,
            occupation_employee2,
            hr_2_ativ,
            name_employee3,
            cod_employee3,
            occupation_employee3,
            hr_3_ativ,
            name_employee4,
            cod_employee4,
            occupation_employee4,
            hr_4_ativ,
            name_employee5,
            cod_employee5,
            occupation_employee5,
            hr_5_ativ,
            name_employee6,
            cod_employee6,
            occupation_employee6,
            hr_6_ativ,
            name_employee7,
            cod_employee7,
            occupation_employee7,
            hr_7_ativ,
            name_employee8,
            cod_employee8,
            occupation_employee8,
            hr_8_ativ,
            name_employee9,
            cod_employee9,
            occupation_employee9,
            hr_9_ativ,
            name_employee10,
            cod_employee10,
            occupation_employee10,
            hr_10_ativ,
            name_employee11,
            cod_employee11,
            occupation_employee11,
            hr_11_ativ,
            name_employee12,
            cod_employee12,
            occupation_employee12,
            hr_12_ativ,
            name_employee13,
            cod_employee13,
            occupation_employee13,
            hr_13_ativ,
            name_employee14,
            cod_employee14,
            occupation_employee14,
            hr_14_ativ,
            name_employee15,
            cod_employee15,
            occupation_employee15,
            hr_15_ativ,
            obs,
            } = request.body;
        const name_leader = request.headers.authorization;
        try{
            const [id] = await connection('rdcs_response').insert({
            area,
            cod,
            obra,
            rain,
            redalert,
            name_leader,            
            area_activity1,           
            cod_activity1,
            description_activity1,
            report1,
            area_activity2,           
            cod_activity2,
            description_activity2,
            report2,
            area_activity3,           
            cod_activity3,
            description_activity3,
            report3,
            area_activity4,           
            cod_activity4,
            description_activity4,
            report4,
            area_activity5,           
            cod_activity5,
            description_activity5,
            report5,
            area_activity6,           
            cod_activity6,
            description_activity6,
            report6,
            name_employee1,
            cod_employee1,
            occupation_employee1,
            hr_1_ativ,
            name_employee2,
            cod_employee2,
            occupation_employee2,
            hr_2_ativ,
            name_employee3,
            cod_employee3,
            occupation_employee3,
            hr_3_ativ,
            name_employee4,
            cod_employee4,
            occupation_employee4,
            hr_4_ativ,
            name_employee5,
            cod_employee5,
            occupation_employee5,
            hr_5_ativ,
            name_employee6,
            cod_employee6,
            occupation_employee6,
            hr_6_ativ,
            name_employee7,
            cod_employee7,
            occupation_employee7,
            hr_7_ativ,
            name_employee8,
            cod_employee8,
            occupation_employee8,
            hr_8_ativ,
            name_employee9,
            cod_employee9,
            occupation_employee9,
            hr_9_ativ,
            name_employee10,
            cod_employee10,
            occupation_employee10,
            hr_10_ativ,
            name_employee11,
            cod_employee11,
            occupation_employee11,
            hr_11_ativ,
            name_employee12,
            cod_employee12,
            occupation_employee12,
            hr_12_ativ,
            name_employee13,
            cod_employee13,
            occupation_employee13,
            hr_13_ativ,
            name_employee14,
            cod_employee14,
            occupation_employee14,
            hr_14_ativ,
            name_employee15,
            cod_employee15,
            occupation_employee15,
            hr_15_ativ,
            obs,

        });

            return response.json({id});
    }catch{
        return response.status(400).json({error: 'Erro ao cadastrar RDC'})
    }
},

    async delete(request, response){
        const {id} = request.params;
  
        await connection('rdcs_response').where('id', id).delete();
  
        return response.status(204).send();
    }
};